### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by lonefly163** [canisminor1990/sd-webui-lobe-theme#100]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 🐛 问题描述 | Bug Description

页面加载时console报错 https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;600&display=swap 无法加载。页面停留在加载等待状态，空的页面框架，没有内容。

### 🚦 期望结果 | Expected Behavior

希望能正常进入系统，不要过于依赖外部资源，如果要引用外部样式表或字体，建议在本地缓存，需要时更新。

**Comment by canisminor1990** [comment]
并没有用到该webfont
