### ISSUE TITLE
[Bug] Scroll doesn't work if Sidebar default expand option is off.

### ISSUE THREAD

**Issue by Pitpe12** [canisminor1990/sd-webui-lobe-theme#111]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

 If the default expand option is not checked, then scroll is impossible inside the Sidebar (and ExtraNetwork Sidebar).

![Screenshot 2023-06-04 195841](https://github.com/canisminor1990/sd-webui-kitchen-theme/assets/68826106/54735fc7-dda2-4504-8a37-f20e7452eedc)

This happens with either fixed or float modes.

If the default expand is checked, then scroll works in both float and fixed modes

### 🚦 期望结果 | Expected Behavior

Scroll should work in both fixed and float modes, regardless of the default expand option.

### 📷 复现步骤 | Recurrence Steps

1. Uncheck default expand
2. Apply and restart
3. Try to scroll inside the Sidebars
4. Scroll doesn't work.

### 📝 补充信息 | Additional Information

There's also a typo at the top
![Screenshot 2023-06-04 201040](https://github.com/canisminor1990/sd-webui-kitchen-theme/assets/68826106/dc144480-ddcf-4b77-9053-f53b202794f8)
I think it should be “Prompt Textarea”?

**Comment by xueqing0622** [comment]
some issue, hope to fix quickly
