### ISSUE TITLE
[Request] ExtraNetwork Sidebar需要滚动条，lora太多显示不全

### ISSUE THREAD

**Issue by pimin12** [canisminor1990/sd-webui-lobe-theme#120]
### 🥰 需求描述 | Feature Description

lora太多显示不全

### 🧐 解决方案 | Proposed Solution

 ExtraNetwork Sidebar需要滚动条

**Comment by anne43983959** [comment]
两个侧边栏全都改成float，用fixed就会导致不显示滚动条

**Comment by pimin12** [comment]
> 两个侧边栏全都改成float，用fixed就会导致不显示滚动条

还是不行，对了，整个网页也没有滚动条

**Comment by anne43983959** [comment]
> > 两个侧边栏全都改成float，用fixed就会导致不显示滚动条
> 
> 还是不行，对了，整个网页也没有滚动条

还要启用默认展开，这个issue我之前提过，你去翻翻就能看见，只有设置成作者的默认参数才能避免bug，非默认参数状态下的bug一直都没修

**Comment by amimi818** [comment]
> > > 两个侧边栏全都改成float，用fixed就会导致不显示滚动条
> > 
> > 
> > 还是不行，对了，整个网页也没有滚动条
> 
> 还要启用默认展开，这个issue我之前提过，你去翻翻就能看见，只有设置成作者的默认参数才能避免bug，非默认参数状态下的bug一直都没修

设成默认（reset）重启之后，再改为float，滚轮由可以用了，看来不是很稳定。
