### ISSUE TITLE
[Bug] 不能加载lobe-theme

### ISSUE THREAD

**Issue by liulsg** [canisminor1990/sd-webui-lobe-theme#149]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/97494068/8411b0c4-5dd0-4e12-b1ec-5f0fa24ec4d3)
1.浏览器标签可正常显示LOGO,但主题不能被加载。
2.重启浏览器及SD仍不能加载
3.版本信息：
version: [v1.4.0] •  python: 3.10.11  •  torch: 2.0.1+cu118  •  xformers: 0.0.19  •  gradio: 3.32.0  •  checkpoint: [9aba26abdf]
LOBE-THENME版本：V2.0.0 (afe89ca)

**Comment by canisminor1990** [comment]
再 pull 下插件最新版试试

**Comment by liulsg** [comment]
> 再拉下插件最新版尝试
最新版已解决！！辛苦
