### ISSUE TITLE
[Request] 

### ISSUE THREAD

**Issue by laignguihua** [canisminor1990/sd-webui-lobe-theme#152]
### 🥰 需求描述 | Feature Description

首先非常感谢制作者提供这么好的软件！
1.更新到2.0版本后，ExraNetworks弹出默认都是一列，设置里定义的“Default width”已经不起作用，每次都需要拖动来拉宽ExraNetworks弹窗非常不便。
2.QuickSetting Sidebar可以选择关闭“Prompt editor”非常好，不过还是希望可以选择把sd_model_checkpoint，sd_vae，CLIP_stop_at_last_ layers，cross_attention_optimization这些放在主菜下方，因为他们的名字长，有希望时刻可以看到这些信息。
3.个人觉得原来“生成”按钮下方的一群按钮还有“风格模板”这些还是放在现在2.0版本的“生成”按钮下方更科学，因为他们短，放在现在2.0版本的位置不仅改变了用户的习惯，只要还是不需要这么大的按钮，反倒占用了重要的主题界面空间。
4.这个我不是知道是bug还是就是这么设计的，我有安装sd-webui-prompt-all-in-one，2.0版本之前和kitchen-theme相处的很好，现在2.0里sd-webui-prompt-all-in-one的关键词输入框变得太大了。

### 🧐 解决方案 | Proposed Solution

都是个人使用上遇到的问题的见解，希望作者可以继续优化这款软件的使用体验，增强兼容性。

### 📝 补充信息 | Additional Information

脚本选择下来菜单里很多脚本都没有了。但脚本文件都没有丢失，这个应该是bug了。

**Comment by liulsg** [comment]
脚本下拉不出现子项目，这个BUG已经修复了，你拉去最新的版本。

**Comment by Physton** [comment]
@laignguihua lobe与sd-webui-prompt-all-in-one的显示问题，sd-webui-prompt-all-in-one那边已经做了兼容。
