### ISSUE TITLE
[Question] 新版本不能用

### ISSUE THREAD

**Issue by YSblack** [canisminor1990/sd-webui-lobe-theme#153]
### 🧐 问题描述 | Proposed Solution

![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/44052382/3fe92698-91bc-4bec-ba2f-6f7eea112b7f)
![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/44052382/05f94337-4d7b-4928-b71e-53fbc4098825)
版本符合要求

**Comment by canisminor1990** [comment]
重新拉取最新版本试试

**Comment by YSblack** [comment]
> 重新拉取最新版本试试

拉取了sd的最新的，也不行
主题最新的也有问题

**Comment by YSblack** [comment]
> 重新拉取最新版本试试

更新sd1.4版本正常了
感谢
