### ISSUE TITLE
[Request] 请移除这些链接

### ISSUE THREAD

**Issue by shiyan8888** [canisminor1990/sd-webui-lobe-theme#154]
### 🥰 需求描述 | Feature Description

感谢你开发了如此好的主题！

我希望你能够移除这些链接：
点击logo跳转到github的链接。
页面底部的链接。

### 🧐 解决方案 | Proposed Solution

无

### 📝 补充信息 | Additional Information

![Snipaste_2023-06-28_13-36-13](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/137896304/e87fa690-f8f8-440c-bee3-3415ed1c4308)
![Snipaste_2023-06-28_13-36-27](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/137896304/a778991b-7789-42d1-a52b-9b96e92b4e89)

**Comment by canisminor1990** [comment]
已添加隐藏footer的设置
