### ISSUE TITLE
[Bug] dropdown white on white

### ISSUE THREAD

**Issue by moonshinegloss** [canisminor1990/sd-webui-lobe-theme#167]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Firefox

### 🐛 问题描述 | Bug Description

inside after detailer (adetailer) dropdown this is unreadable:

![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/118488816/28c090c8-d7ab-4b75-8fbb-eecf9f93c5fc)

**Comment by esbe1175** [comment]
Can confirm this happens on Chrome as well
![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/1612897/5940620c-d87e-4ebb-9390-1ac54ddbcbcb)

**Comment by nightflier** [comment]
Also happening on Safari (16.5.1 on MacOS Ventura 13.4.1)
<img width="549" alt="Screenshot 2023-06-28 alle 22 55 50" src="https://github.com/canisminor1990/sd-webui-lobe-theme/assets/1293107/9aef2d09-278e-4415-aa80-6e6705af5206">

**Comment by nightflier** [comment]
still not working despite latest commits by @canisminor1990 
am I doing something wrong?
<img width="963" alt="Screenshot 2023-06-30 alle 22 23 21" src="https://github.com/canisminor1990/sd-webui-lobe-theme/assets/1293107/688ebdd1-111a-444f-8418-8964f6807aa7">
