### ISSUE TITLE
[Bug] selected dropdown items white on white

### ISSUE THREAD

**Issue by moonshinegloss** [canisminor1990/sd-webui-lobe-theme#169]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Firefox

### 🐛 问题描述 | Bug Description

here's an example but this also happens in all other dropdowns across the UI:

![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/118488816/ae92c6b0-92a8-490b-b942-da76d229e584)

![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/118488816/ea382252-9794-4322-9ad4-22d08829e9dd)

**Comment by esbe1175** [comment]
On chrome, this hjappens with the first option that fits the search criteria:
![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/1612897/0403686e-d589-4f4f-875f-f05b89755b28)

Hovering, so you can see what's underneath:
![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/1612897/2bb16925-a5fc-4eb5-a0aa-d9f73d4cd6ee)

**Comment by canisminor1990** [comment]
#167

**Comment by nightflier** [comment]
bug still happening on macos
