### ISSUE TITLE
[Bug] 动态界面内容占用了大量资源

### ISSUE THREAD

**Issue by anne43983959** [canisminor1990/sd-webui-lobe-theme#171]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

从6月18日发布的e9e51e6版本更新到6月28日发布的最新版，启动后CPU占用率激增，可以明显在任务管理器观察到控制台和浏览器的进程占用了40%的CPU资源，风扇噪音也随之激增（CPU是i9-13980HX，关闭小核）
与此同时，打开浏览器，显卡占用率也会上升到40%左右，虽然对出图时间无影响，但是进一步恶化了功耗和散热条件（4090Laptop，初始测试约2.4秒，更新后简单在相同条件下测试，时间为2.6秒）

### 🚦 期望结果 | Expected Behavior

对于任何额外占用资源，都应该设置独立的开关，CozyNest主题已经在这个问题是吃过亏了，动态背景，尤其是实时计算的动态背景，会占用大量资源
作为界面美化插件，还是应该将重心放在更加友好易用的ui界面上，而不是视觉效果的堆叠

### 📷 复现步骤 | Recurrence Steps

启动，观察任务管理器资源占用，回滚到6月18日的版本，再启动，对比资源占用的差异

**Comment by canisminor1990** [comment]
#161, 正在增加开关

**Comment by anne43983959** [comment]
感谢对建议的采纳，现在CPU占用率已经恢复正常
