### ISSUE TITLE
[Bug] Right sidebar expand issue

### ISSUE THREAD

**Issue by Aosneg** [canisminor1990/sd-webui-lobe-theme#172]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 🐛 问题描述 | Bug Description

Right sidebar expand when mouse reaches scrollbar area doesn't work as intended. It closes and opens when I move the mouse to the left. At least, in Edge and Brave.

### 🚦 期望结果 | Expected Behavior

Right sidebar expands when mouse reaches scrollbar area.

### 📷 复现步骤 | Recurrence Steps

https://github.com/canisminor1990/sd-webui-lobe-theme/assets/138026259/31cadad7-22ba-432b-91e8-02bf5dfbc808

**Comment by esbe1175** [comment]
Do you have another monitor extending past the right border? Probably happens because your cursor leaves the browser.

**Comment by amimi818** [comment]
I have the same problem

**Comment by Zullian** [comment]
I can confirm the same problem, 1 monitor, windows/chrome.
