### ISSUE TITLE
[Request] 

### ISSUE THREAD

**Issue by Hosiokaa** [canisminor1990/sd-webui-lobe-theme#176]
### 🥰 需求描述 | Feature Description

The ability to remove RGB Breathing colors in the background and replace with flat colors. aswell as change the interrupt/skip button colors. lastly removing the _**Rainbow loading bar**_ and replacing with a flat color of choice.

These are QOL features nothing big. but Please remove the LGBT loading bar 🙏
![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/118495208/fcd62f95-26c1-4b63-bdba-725a542a81ef)

### 🧐 解决方案 | Proposed Solution

1. Ability to remove breathing RGB background colors and replace with background itself.
2. Ability to change interrupt/skip buttons from default pink to red(or a chosen color from the user)
3. PLEASE LET ME GET RID OF THE LGBT RAINBOW LOADING BAR🙏

### 📝 补充信息 | Additional Information

This is an QOL issue and shouldn't be on top of the list. Please take a look once you're able to.

**Comment by canisminor1990** [comment]
you can find remove animation options in setting panel

**Comment by Hosiokaa** [comment]
If possible I would love to keep the animations itself especially when switching tabs. im not sure if turning off the animations turns those off but. If so my main gripe would be the interrupt buttons being pink as default. how can I change that

**Comment by Hosiokaa** [comment]
Thank you for removing the LGBT loading bar. I will now close the Issue with this.
🤝
