### ISSUE TITLE
[Bug] 無法使用canvas放大功能

### ISSUE THREAD

**Issue by KohakuBlueleaf** [canisminor1990/sd-webui-lobe-theme#177]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 🐛 问题描述 | Bug Description

如題
使用sd-webui內建的放大功能的時候會被遮擋
![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/59680068/bccc5c5b-fc8d-40ba-b49b-feb56984e096)

### 🚦 期望结果 | Expected Behavior

正常使用放大功能

### 📷 复现步骤 | Recurrence Steps

進入img2img頁面
使用inpaint/sketch/inpaint sketch模式 
按下ctrl+s觸發放大模式

**Comment by amimi818** [comment]
是有这个问题。controlnet画布下的放大也有这个问题，不知道是不是因为不同的Blocks造成的。

另外，convas zoom直接按字母“s”就可以放大，不加Ctrl也可以。@KohakuBlueleaf

<img width="1755" alt="image" src="https://github.com/canisminor1990/sd-webui-lobe-theme/assets/133093934/c8771e49-ae72-4689-be3e-7237482e74ef">

**Comment by KohakuBlueleaf** [comment]
我這應該是有其他的插件擋住這個快捷鍵了
反正就是放大就不行（

**Comment by amimi818** [comment]
升级到最新版本的WebUI（v1.4.0）和Kitchen插件（v2.4.0）后，可以正常放大了。
