### ISSUE TITLE
[Request] 希望重新添加一个和旧版相似的渐变色静态背景

### ISSUE THREAD

**Issue by anne43983959** [canisminor1990/sd-webui-lobe-theme#193]
### 🥰 需求描述 | Feature Description

关闭动态背景后，背景变成纯色，感觉有些单调，希望能添加一个选项恢复以前的渐变色静态背景

### 🧐 解决方案 | Proposed Solution

暂无具体解决方案

**Comment by canisminor1990** [comment]
Done with  https://github.com/canisminor1990/sd-webui-lobe-theme/commit/4fdf4a8b32a5add5d7e826024ea050ec6569d862
