### ISSUE TITLE
[Bug] 语法高亮问题

### ISSUE THREAD

**Issue by liulsg** [canisminor1990/sd-webui-lobe-theme#194]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

1.开启语法高亮后不能自动变更提示词信息，必须敲一下回车键才能显示变更信息。
比如：某个提示词增加权重后并不会自动更改，需要手动敲一下回车键才能在提示词输入框正确的显示。

2.高亮显示与[sd-webui-prompt-all-in-one]插件会起冲突

3.右侧模型等卡片信息会偶尔不显示，因不能判断问题点，所以没法提供复现BUG的方式。

**Comment by amimi818** [comment]
是的，高亮显示模式下与[sd-webui-prompt-all-in-one]插件的适配有问题。

**Comment by 350640267** [comment]
语法高亮显示模式与Dynamic Prompts也有冲突
