### ISSUE TITLE
[Bug] Network panel starts as "Loading..." requires clicking Refresh button

### ISSUE THREAD

**Issue by swieder227** [canisminor1990/sd-webui-lobe-theme#197]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

When I open the network panel, it will display text "Loading..." until I press the network sidebar "Refresh" button. Then all my LORAs etc are displayed.

If I disable `sd-web-ui-kitchen-theme`, the LORA cards load initially as expected in the default theme.

<img width="1691" alt="Screenshot 2023-07-01 at 2 32 06 AM" src="https://github.com/canisminor1990/sd-webui-lobe-theme/assets/1713558/89ccbcae-2248-475c-8dda-8972ebea0378">

### 🚦 期望结果 | Expected Behavior

Upon opening the network sidebar, I'd see all of the LORA cards.

### 📷 复现步骤 | Recurrence Steps

* Start `./webui.sh`
* Open network panel
* See "Loading..."
* Press "Refresh" button
* Now LORA cards are displayed

### 📝 补充信息 | Additional Information

**Versions**
* stable-diffusion-webui = `tag/v1.4.0` (also reproduced on `v1.3.2`)
* sd-web-ui-kitchen-theme = `ec31ef62`

-- 

**Side Note:** It appears `stable-diffusion-webui@v1.4.0` added a new sorting dropdown to NetworkPanel. The dropdown label breaks the UI layout. FWIW, I noticed in Chrome DevTools that the dropdown label has CSS classes `sr-only hide` (sr usually is shorthand for screen-reader), which indicates it's meant to be hidden, but the classes `sr-only hide` do not appear to have any styles defined in this theme. [Example `sr-only` styles from Tailwind](https://tailwindcss.com/docs/screen-readers)

<img width="1333" alt="Screenshot 2023-07-01 at 2 32 22 AM" src="https://github.com/canisminor1990/sd-webui-lobe-theme/assets/1713558/94bf2b0a-009d-405a-996a-7585c2c94527">

**Comment by canisminor1990** [comment]
try the lastest lobe version ?

**Comment by swieder227** [comment]
Oh yes, my apologies. Updated and issue is resolved.

I was running "Check for updates" in the Automatic111 UI and it was not finding new updates – I see that status was "Unknown" not "latest". Going into the extensions folder and running `git pull main` resolved.

Thanks for all the hard work on this theme, it looks spectacular!
