### ISSUE TITLE
The UI appears blank after loading in the browser

### ISSUE THREAD

**Issue by midnight-god-01** [canisminor1990/sd-webui-lobe-theme#198]
The new update that was uploaded 2 hours ago causes the UI to be fully blank. There are no errors shown in the command prompt or anywhere else, but when you open your browser, the UI appears blank. I have everything fully updated and I am running it on Chrome browser.

The only way to access the UI again is to manually delete the theme folder from the extensions folder. 

Please fix the issue ..

**Comment by mccabedd** [comment]
Having exactly the same issue. Had to delete the Lobe extension folder and currently running on the default theme.

**Comment by midnight-god-01** [comment]
I had the same experience. I updated my SD via the git pull command and run the Web UI script, everything was normal when I opened it. Then I updated the extensions, and lo and behold, the UI appeared blank. At first, I thought it was an SD issue because they added another subfolder for LoRA, but then I thought I'd try deleting the theme folder. Sure enough, everything started working normally again. However, even after deleting the entire folder, some theme elements are still present, such as the UI logo in the browser tab icon.

**Comment by cratom4** [comment]
Instead of deleting, you could go to stable diffusion folder, open config file, find "disabled_extensions" and change line like this,

    "disabled_extensions": ["sd-web-ui-kitchen-theme"],

**Comment by midnight-god-01** [comment]
same thing dude .. if a re-installation doesn't fix the issue there may be some optimization error happening .. simply disabling stuff won't, fix issues here ...

**Comment by Tobe2d** [comment]
+1
