### ISSUE TITLE
[Bug] Theme settings button missing in portrait 

### ISSUE THREAD

**Issue by robonxt** [canisminor1990/sd-webui-lobe-theme#210]
### 💻 系统环境 | Operating System

Other

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

On mobile portrait, the settings button is missing and only showing the light/dark theme button.

![Screenshot_2023-07-01-14-17-02-44_7bf062b6cfa832b34bb8e1c056ab1fa0](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/8854735/b5cde3e7-e21f-4a6d-8797-a86a2ed27bb6)

### 🚦 期望结果 | Expected Behavior

Perhaps an option for this, but maybe default to settings icon only, but can change visible icons? (This seems to be useful for desktop/landscape too!)

### 📷 复现步骤 | Recurrence Steps

1. Install theme
2. Open webui in mobile portrait
3. Noice theme button but no settings button

### 📝 补充信息 | Additional Information

As above, perhaps default to showing setting button for mobile, but with ability to change what icons can be shown? (Would love to see this on desktop/landscape too!)

Portrait:
![Screenshot_2023-07-01-14-17-02-44_7bf062b6cfa832b34bb8e1c056ab1fa0](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/8854735/a90b0459-406a-400c-8e44-26a4b4a0802d)

Landscape/Desktop:
![Screenshot_2023-07-01-14-17-22-65_7bf062b6cfa832b34bb8e1c056ab1fa0](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/8854735/d261f1b4-3da7-45c7-925e-a7c20773f729)

**Comment by SirVeggie** [comment]
I also considered opening an issue for this but it seemed intentional. However I do support that the settings button is also included in portrait mode as there seems to be enough space for it anyway.

**Comment by robonxt** [comment]
Working now. Thank you!
