### ISSUE TITLE
[Bug] Interactions with wildcards doesn't work

### ISSUE THREAD

**Issue by IDRAYNAR** [canisminor1990/sd-webui-lobe-theme#217]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 🐛 问题描述 | Bug Description

Hello, I am having some issues with theses two extensions on the Lobe theme, I cant interact with the wildcards, click doesn't work and the arrows keys too.

https://github.com/AUTOMATIC1111/stable-diffusion-webui-wildcards
https://github.com/DominikDoom/a1111-sd-webui-tagcomplete

### 🚦 期望结果 | Expected Behavior

I would like to interact with the wildcards, normally I can click on them or interact with them using the arrow keys of my keyboard.

### 📷 复现步骤 | Recurrence Steps

Two examples, one with a click and the other with the keys. It just closes the wildcard, no interaction at all. :(
<hr>

https://github.com/canisminor1990/sd-webui-lobe-theme/assets/75629737/c3d57ac9-1b16-4f14-8535-0118d4126cbe

**Comment by robonxt** [comment]
@IDRAYNAR I found out that if you have "Prompt Syntax Highlighting" enabled, it does not work. However if you turn it off, autocomplete (and possibly wildcards) works again

![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/8854735/2c345b06-6050-4cf2-a563-0560184ae641)
(make sure "Prompt Syntax Highlighting" is turned off just like in the image)

**Comment by IDRAYNAR** [comment]
I turned off the setting from the screen and its working, thank you! I am going to take a look at the priority to try to have both things activated.

**Comment by robonxt** [comment]
Please do keep us updated! I also would love to have both working at the same time 😅
