### ISSUE TITLE
[Bug] Pasting an image doesn't work or is very inconsistent

### ISSUE THREAD

**Issue by Mozoloa** [canisminor1990/sd-webui-lobe-theme#225]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

Pasting an image doesn't work or is very inconsistent

### 🚦 期望结果 | Expected Behavior

Pasting should just paste the image as an input in the img 2 img tabs

### 📷 复现步骤 | Recurrence Steps

Go to img 2 img, any tab, and try pasting an image

**Comment by SirVeggie** [comment]
Please edit your issue so it includes a relevant title.
