### ISSUE TITLE
[Bug] The installed tab of the extension interface keeps loading and does not display properly.

### ISSUE THREAD

**Issue by nima666-jj** [canisminor1990/sd-webui-lobe-theme#231]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

The installed tab of the extension interface keeps loading and does not display properly.
![QQ截图20230706113055](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/62422839/87a1afa7-3fcc-4d31-9c5b-8deac605e05e)

**Comment by sha7dowXX** [comment]
firefox too
