### ISSUE TITLE
[Bug] 快捷键消失

### ISSUE THREAD

**Issue by vjleoliu** [canisminor1990/sd-webui-lobe-theme#241]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 🐛 问题描述 | Bug Description

1、消失的快捷键
我发现很多人都没有注意，SD出图是有快捷键的（ctrl+enter），这样大大提高操作的效率，但在使用lobe theme的时候，这个快捷键消失了，无论在tex2img还是img2img中。同时，如果可以的话，希望大佬可以多设置一些快捷键，让SD更加快捷。
2、消失的标签自动补全
如您所见，我是中文用户，SD的中文标签补全对我来说非常重要，但在lobe theme中，对它的支持似乎并不好
一则是在我输入tag时补全工具出现的下拉列表中，无法高亮显示我所选择的tag，而是隔行高亮显示，这让人非常困惑，无法直观的看到自己选择的哪一行的tag（键盘操作时）
二则是在使用prompt-all-in-one这款插件时，它有一个tag输入框，通常输入时同样会有tag补全的下拉列表，但它在lobe中消失了，无论输入中文还是英文，都没有下拉列表出现。
3. 不情之请
双列模式很好用，但感觉可以更好用，不知大佬是否考虑将生成图片的区域窗口化（独立的一个悬浮窗口）这样设置参数的区域，无论上下如何滚动都不影响观察结果，之所以有这个不情之请，是因为我曾经是个3d设计师，而sd的操作和3d很像，即设置各种参数，然后开始渲染查看结果，这样会更加高效，不知lobe是否能做到如此调整，也希望lobe越来越好用

以上是我使用lobe一段时间的真实感受，谢谢大佬的无私奉献，也希望lobe越来越好，越来越多人用上如此便捷美观的ui

**Comment by anne43983959** [comment]
ctrl+enter这个功能在cb7f77e版本是正常的，之后的版本除了快捷键失效，设置也失效了

**Comment by anne43983959** [comment]
tag补全在cb7f77e版本也能正常使用

**Comment by vjleoliu** [comment]
所以要退回到之前的版本才能正常使用是吗？
