### ISSUE TITLE
[Bug] 插件与设置失效

### ISSUE THREAD

**Issue by anne43983959** [canisminor1990/sd-webui-lobe-theme#243]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

将插件版本更新到af6ae27及之后的版本时，出现Controlnet插件报错和Lobe插件本身设置无法保存，旧设置丢失的bug，严重影响使用

### 🚦 期望结果 | Expected Behavior

尽快解决lobe插件本身无法保存设置的问题，有可能的话查明与Controlnet插件冲突的原因，从功能性角度，Controlnet高于lobe，因此这个bug会导致大量用户停留在cb7f77e版本拒绝更新

### 📷 复现步骤 | Recurrence Steps

从cb7f77e版本更新到af6ae27或者2d9472版本，当出现设置丢失的情况即可复现

**Comment by anne43983959** [comment]
另外，回滚到cb7f77e版本甚至可以恢复旧设置，推测是读取设置文件的功能出现问题

**Comment by wqjuser** [comment]
报错的只是sd-webui-lobe-theme这个扩展，controlnet只是显示在上面而已

**Comment by canisminor1990** [comment]
fixed
