### ISSUE TITLE
[Bug] 提示词输入界面的光标位置不对

### ISSUE THREAD

**Issue by yuno779** [canisminor1990/sd-webui-lobe-theme#245]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/131428984/ea443115-d3cd-45e7-a59c-402990e96edb)
![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/131428984/9a2afa85-cce9-4752-9276-2e4e25249060)
提示词越长光标位置错位越严重，第二张图是复制了两遍提示词用以展示bug

**Comment by zatt** [comment]
I think I still have this exact bug on Windows. (everything up to date: Lobe - SD - Brave browser [a Chrome based browser] ). 

For me, the highlighting is all wrong and I have to resize the prompt box constantly to 'fix' it. I click somewhere and it starts typing elsewhere. I can't read the language above, but it seems to be the same issue?



Anyway, thanks so much for this theme, fantastic UI. Indispensable!
