### ISSUE TITLE
[Bug] 使用语法高亮时,无法使用ctrl快捷键增减提示词权重

### ISSUE THREAD

**Issue by luuIlee** [canisminor1990/sd-webui-lobe-theme#247]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 🐛 问题描述 | Bug Description

![Snipaste_2023-07-09_15-29-03](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/34571277/ae38cd3e-6a10-46c1-9c88-7c476e576348)

### 📷 复现步骤 | Recurrence Steps

 当开启语法高亮时,ctrl快捷键增减提示词权重失效.

**Comment by Dragoy** [comment]
I join in the problem! The Tag Autocomplete plugin's dropdown selection also doesn't work.
![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/4968313/7e1743b6-6915-4c1f-9689-3c679f79639b)

**Comment by Dragoy** [comment]
Thanks for the quick fix of the previous bug. but I forgot to mention one cosmetic fix that highlights the items in the menu one by one like here in the video
https://github.com/canisminor1990/sd-webui-lobe-theme/assets/4968313/cbbd72fd-edc4-4526-94cb-f0ac070cc6b1

**Comment by Dragoy** [comment]
> Thanks for the quick fix of the previous bug. but I forgot to mention one cosmetic fix that highlights the items in the menu one by one like here in the video

@canisminor1990 did you get a chance to check it out?
