### ISSUE TITLE
How do we customize?

### ISSUE THREAD

**Issue by bbecausereasonss** [canisminor1990/sd-webui-lobe-theme#25]
I want to change a few colors, buttons/highlights, font colors? Where can we do this? Thanks!

**Comment by bbecausereasonss** [comment]
Also is there a way to wrap the top options panels? Mine don't wrap like in the original UI, and I have a bunch of extra settings that now require a very long window to see.

**Comment by applesugarai** [comment]
> Also is there a way to wrap the top options panels? Mine don't wrap like in the original UI, and I have a bunch of extra settings that now require a very long window to see.

Same here. Otherwise I really like the theme. I just can't use it easily without being able to do this.

**Comment by Bodzijun** [comment]
You can also add the ability to drag and drop extension tabs (both in the interface header and directly in the application window to organize the functionality)

**Comment by prescience-data** [comment]
You can edit `extensions/sd-web-ui-kitchen-theme/theme/style.css` (or use the `.less` files in the repo to regenerate it). If you aren't familiar with editing CSS directly, you can give ChatGPT a fairly unstructured dump of theme colors, and then provide the raw content from `style.css` and it will do an "ok" job of replacement.
