### ISSUE TITLE
安装插件后图像生成速度变慢10%[Bug] 

### ISSUE THREAD

**Issue by Aodamiao413** [canisminor1990/sd-webui-lobe-theme#267]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

未安装主题插件或安装原kitchen插件时，我的2080Ti显卡生成速度：512*512默认参数下，出图速度为**13.8it/s**，切换lobe主题后，生成速度降为**12it/s**，替换回kitchen插件后，速度恢复。

**Comment by canisminor1990** [comment]
设置-减弱动效
