### ISSUE TITLE
[Bug] 深色模式的问题

### ISSUE THREAD

**Issue by idesign2018** [canisminor1990/sd-webui-lobe-theme#268]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/42263070/029eef1a-5ef7-48a5-9424-9060bba0c5b9)
在云端安装插件后，每次启动都是浅色模式，需要手动设置深色模式，即使设置了深色模式，下次启动还是浅色模式，希望能得到优化

### 🚦 期望结果 | Expected Behavior

希望可以在设置中设置深色模式，一打开就是深色模式

**Comment by canisminor1990** [comment]
![image](https://github.com/canisminor1990/sd-webui-lobe-theme/assets/17870709/c1ce49f0-3258-4125-861d-5d5077acb777)

**Comment by idesign2018** [comment]
我是在autodl.com平台上部署的SD，安装咱们这个插件后，每次都需要手动设置深色模式，哪怕我在bat文档中强制深色模式，还是会显示浅色模式，只有手动在我们主题点击深色模式后，才会刷新为深色模式，就是很奇怪
