### ISSUE TITLE
[Bug] 点击左上角设置然后整个界面白屏！

### ISSUE THREAD

**Issue by liulsg** [canisminor1990/sd-webui-lobe-theme#276]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

正常启动后所有社会恢复成了默认，点击左上角设置按钮整个界面白屏

AttributeError: 'Namespace' object has no attribute 'lobe_debug'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by canisminor1990** [comment]
更到最新了么？

**Comment by SPNK78** [comment]
same issue, ive just downloaded the last version.
