### ISSUE TITLE
[Bug] arrow::fs::FinalizeS3 was not called even though S3 was initialized.

### ISSUE THREAD

**Issue by Amazon90** [canisminor1990/sd-webui-lobe-theme#280]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

microsoft edge

### 🐛 问题描述 | Bug Description

https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/11827

Extensions tab Click "Apply and restart webUI"
C:\arrow\cpp\src\arrow\filesystem\s3fs.cc:2598: arrow::fs::FinalizeS3 was not called even though S3 was initialized. This could lead to a segmentation fault at exit

### 🚦 期望结果 | Expected Behavior

repair it plz

### 📷 复现步骤 | Recurrence Steps

1.open webui-user.bat
2.Extensions tab Click "Apply and restart webUI"

**Comment by w-e-w** [comment]
sorry I might have misread
the bug may not originate from lobe
