### ISSUE TITLE
[Request] Make "Generate" button stationary

### ISSUE THREAD

**Issue by rexorp** [canisminor1990/sd-webui-lobe-theme#69]
### 🥰 需求描述 | Feature Description

Many extensions make the page too long. Taking long time to scroll up over and over when making changes on the fly. Especially for changing setting on the extensions that are on the bottom of the page. Would allow for making changes faster with out having to scroll up at all.

### 🧐 解决方案 | Proposed Solution

Make "Generate" button stationary.

### 📝 补充信息 | Additional Information

Honestly, I often don't see and always forget about using the auto scroll up button.

**Comment by canisminor1990** [comment]
https://github.com/canisminor1990/sd-webui-kitchen-theme/issues/39
