### ISSUE TITLE
[Request] 希望加强对Civitai Helper的支持

### ISSUE THREAD

**Issue by anne43983959** [canisminor1990/sd-webui-lobe-theme#77]
### 🥰 需求描述 | Feature Description

当前版本下，使用附加网络侧边栏时，依然存在Civitai Helper的刷新按钮失效问题，仅刷新网页后显示的第一种附加网络有Civitai Helper的空间按钮，切换到其他种类附加网络、添加预览图、刷新模型，都会导致Civitai Helper的控件失效后无法通过其自带的刷新按钮重新恢复
现在Civitai Helper已经进入维护阶段，希望后续版本加强对Civitai Helper的兼容，并做好兼容其2.0版本Model info helper的准备

### 🧐 解决方案 | Proposed Solution

暂无明确解决方案

### 📝 补充信息 | Additional Information

仅在Chrome上测试过，不清楚edge和Safari的情况

**Comment by onlineman1978** [comment]
edge上同样的问题，求兼容

**Comment by Isaiahfeldt** [comment]
+1 :+1:

**Comment by Array-Cats** [comment]
目前能够有效的临时解决方式就是使用底部的重载界面（Reload UI），至少Chrome下是有效的
