### ISSUE TITLE
[Request] 顶部栏能否更改为自定义顺序

### ISSUE THREAD

**Issue by yuno779** [canisminor1990/sd-webui-lobe-theme#86]
### 🥰 需求描述 | Feature Description

![image](https://github.com/canisminor1990/sd-webui-kitchen-theme/assets/131428984/65b41e0e-a4ee-4eba-b6a4-804151f0b653)

最新更新的版本折叠了一部分模块卡片栏，这导致了我常用的一部分选项卡被隐藏了实际使用经常点不到非常难受。能否增加一个自定义顺序的功能

### 🧐 解决方案 | Proposed Solution

![image](https://github.com/canisminor1990/sd-webui-kitchen-theme/assets/131428984/f66c84ee-66f1-461d-8006-cf46538d42f5)
neng
设置为更改自定义顺序就好了

**Comment by angelineage** [comment]
这个功能在WebUI的设置里面，你甚至可以隐藏不常用的标签
<img width="1770" alt="image" src="https://github.com/canisminor1990/sd-webui-kitchen-theme/assets/128225199/5369a6bb-e6ab-4789-968b-ccc19cc59e27">
