### ISSUE TITLE
[Bug] Safari环境下的UI显示问题

### ISSUE THREAD

**Issue by angelineage** [canisminor1990/sd-webui-lobe-theme#87]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Safari

### 🐛 问题描述 | Bug Description

界面初次加载后，TOP栏会处于最大化的状态，需要手动拉上去。调整后开关相关功能内容才会显示出来。
<img width="1513" alt="截屏2023-05-20 10 19 59" src="https://github.com/canisminor1990/sd-webui-kitchen-theme/assets/128225199/4f4afa13-ac65-4d7f-a112-b1cb857b6707">
<img width="1513" alt="截屏2023-05-20 10 24 19" src="https://github.com/canisminor1990/sd-webui-kitchen-theme/assets/128225199/f98dcf95-7862-46f2-864b-0fcaeea96ab0">
<img width="1513" alt="截屏2023-05-20 10 33 36" src="https://github.com/canisminor1990/sd-webui-kitchen-theme/assets/128225199/af9e0aff-8690-4b11-9f57-acd9498de8bd">

### 🚦 期望结果 | Expected Behavior

希望能修复次问题

### 📝 补充信息 | Additional Information

Safari版本16.4/16.5，
同操作系统下EDGE和Chrome无此问题。

**Comment by amimi818** [comment]
I have the same problem in safari

**Comment by calonye** [comment]
是的，我之前遇到同样的问题，目前插件版本更至最新了，问题依旧～但我看分支提交更新，貌似有解决问题，但不知道为什么问题依旧～

**Comment by yuhuanowo** [comment]
基於最新版本，ipad版的safari和chrome不管是否開啟電腦版網頁都會遇到此問題

**Comment by angelineage** [comment]
新版已经解决此问题
